name = "tarot-api"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

# Variables de entorno para el login del panel admin
[vars]
ADMIN_USERNAME = "venezuela"
ADMIN_PASSWORD = "venezuela"

# Base de datos D1
[[d1_databases]]
binding = "DB"
database_name = "tarot-database"
database_id = "b85548ef-048f-45eb-bd83-91d97a2ca21f"
